/**
 * OLKIL Auth — shared contracts (Cursor/Trae-style browser login).
 *
 * Flow:
 * 1. IDE starts a loopback HTTP listener (RFC 8252) and opens olkil.com/auth/ide
 * 2. User signs in with Firebase on the website
 * 3. Website redirects to http://127.0.0.1:<port>/callback with tokens + state
 * 4. IDE verifies state, stores session, closes the loopback server
 */

export const OlkilAuthNodeServicePath = 'OlkilAuthNodeServicePath';
export const IOlkilAuthNodeService = 'IOlkilAuthNodeService';
export const IOlkilAuthService = 'IOlkilAuthService';

/** Virtual editor scheme for the OLKIL Account tab (Cursor Settings–style). */
export const OLKIL_ACCOUNT_SCHEME = 'olkil-account';

/** Public Firebase web config (restricted by Auth domain allowlist). */
export const OLKIL_FIREBASE_CONFIG = {
  apiKey: 'AIzaSyA3z0FDMJrfskddGj4Iair9D2XH3K_IS2k',
  authDomain: 'olkil-2c8ac.firebaseapp.com',
  projectId: 'olkil-2c8ac',
  storageBucket: 'olkil-2c8ac.firebasestorage.app',
  messagingSenderId: '781364120676',
  appId: '1:781364120676:web:b95ff8f1839b3a0b0aa371',
  measurementId: 'G-77ZW0JFXSB',
} as const;

/** Firestore project used for per-user agent chat history (max 3 / 48h). */
export const OLKIL_FIRESTORE_PROJECT = OLKIL_FIREBASE_CONFIG.projectId;

export const OLKIL_AUTH_WEB_ORIGIN = 'https://olkil.com';
export const OLKIL_AUTH_IDE_PATH = '/auth/ide/';
export const OLKIL_PROTOCOL_SCHEME = 'olkil';
export const OLKIL_AUTH_CREDENTIAL_SERVICE = 'olkil-auth';
export const OLKIL_AUTH_CREDENTIAL_ACCOUNT = 'session';

export interface OlkilAuthUser {
  uid: string;
  email: string | null;
  displayName: string | null;
  photoURL: string | null;
  emailVerified: boolean;
}

export interface OlkilAuthSession {
  user: OlkilAuthUser;
  idToken: string;
  refreshToken: string;
  /** Epoch ms when idToken was issued / last refreshed */
  obtainedAt: number;
  expiresAt: number;
}

export interface OlkilAuthLoginRequest {
  /** CSRF / correlation token generated by the IDE */
  state: string;
  /** Loopback redirect, e.g. http://127.0.0.1:54321/callback */
  redirectUri: string;
}

export interface OlkilAuthCallbackPayload {
  state: string;
  idToken: string;
  refreshToken: string;
}

export interface OlkilAuthLoopbackResult {
  port: number;
  redirectUri: string;
}

export interface IOlkilAuthNodeService {
  /** Start ephemeral 127.0.0.1 listener; resolves when callback received or timeout. */
  beginLoginFlow(state: string, timeoutMs?: number): Promise<OlkilAuthLoopbackResult>;
  /** Wait for the browser callback (after beginLoginFlow). */
  waitForCallback(state: string): Promise<OlkilAuthCallbackPayload>;
  /** Cancel pending login and close listener. */
  cancelLoginFlow(): Promise<void>;
  /** Persist session to disk under user data dir. */
  saveSession(session: OlkilAuthSession): Promise<void>;
  loadSession(): Promise<OlkilAuthSession | null>;
  clearSession(): Promise<void>;
  /** Refresh ID token via Google Secure Token API. */
  refreshIdToken(refreshToken: string): Promise<{ idToken: string; expiresIn: number }>;
}

export interface IOlkilAuthService {
  getSession(): OlkilAuthSession | null;
  getUser(): OlkilAuthUser | null;
  isSignedIn(): boolean;
  /** Opens browser to olkil.com and completes IDE callback. */
  signIn(): Promise<OlkilAuthSession>;
  signOut(): Promise<void>;
  /** Ensure a fresh idToken (refresh if near expiry). */
  getValidIdToken(): Promise<string | null>;
  onDidChangeSession(listener: (session: OlkilAuthSession | null) => void): { dispose: () => void };
}

export function buildIdeAuthUrl(params: {
  state: string;
  redirectUri: string;
  origin?: string;
}): string {
  const origin = (params.origin || OLKIL_AUTH_WEB_ORIGIN).replace(/\/$/, '');
  const url = new URL(`${origin}${OLKIL_AUTH_IDE_PATH}`);
  url.searchParams.set('state', params.state);
  url.searchParams.set('redirect_uri', params.redirectUri);
  url.searchParams.set('client', 'olkil-ide');
  url.searchParams.set('protocol', OLKIL_PROTOCOL_SCHEME);
  return url.toString();
}

export function createAuthState(): string {
  const bytes = new Uint8Array(24);
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
    crypto.getRandomValues(bytes);
  } else {
    for (let i = 0; i < bytes.length; i++) {
      bytes[i] = Math.floor(Math.random() * 256);
    }
  }
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

/** Decode JWT payload without verifying (server/REST verifies separately). */
export function decodeJwtPayload(token: string): Record<string, unknown> | null {
  try {
    const part = token.split('.')[1];
    if (!part) {
      return null;
    }
    const normalized = part.replace(/-/g, '+').replace(/_/g, '/');
    const json =
      typeof Buffer !== 'undefined'
        ? Buffer.from(normalized, 'base64').toString('utf8')
        : decodeURIComponent(
            atob(normalized)
              .split('')
              .map((c) => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2))
              .join(''),
          );
    return JSON.parse(json);
  } catch {
    return null;
  }
}

export function sessionFromTokens(
  idToken: string,
  refreshToken: string,
  obtainedAt = Date.now(),
): OlkilAuthSession | null {
  const payload = decodeJwtPayload(idToken);
  if (!payload || typeof payload.user_id !== 'string' && typeof payload.sub !== 'string') {
    return null;
  }
  const uid = String(payload.user_id || payload.sub);
  const expSec = typeof payload.exp === 'number' ? payload.exp : obtainedAt / 1000 + 3600;
  return {
    user: {
      uid,
      email: typeof payload.email === 'string' ? payload.email : null,
      displayName: typeof payload.name === 'string' ? payload.name : null,
      photoURL: typeof payload.picture === 'string' ? payload.picture : null,
      emailVerified: payload.email_verified === true,
    },
    idToken,
    refreshToken,
    obtainedAt,
    expiresAt: expSec * 1000,
  };
}
